### ISSUE TITLE
AttributeError: 'Executor' object has no attribute '__proxied_object'

### ISSUE THREAD

**Issue by ZairMahmood** [dchevell/flask-executor#16]
```
from flask import Flask, jsonify
from flask_executor import Executor
from time import sleep

app = Flask(__name__)
executor = Executor()

print(executor)

executor.init_app(app)

@executor.job
def print_something_after_time(time, text):
    sleep(time)
    print(text)
    return True

@app.route('/')
def start_task():
    print_something_after_time.submit(3, "test")
    return jsonify({'result':'success'})
```

referencing executor before initializing it with the app throws the following error:

```
Traceback (most recent call last):
  File "~/bin/flask", line 10, in <module>
    sys.exit(main())
  File "~/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "~/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "~/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "~/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "~/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "~/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "~/lib/python3.7/site-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "~/lib/python3.7/site-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "~/lib/python3.7/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "~/lib/python3.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "~/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/zair/Desktop/test.py", line 8, in <module>
    print(executor)
  File "~/lib/python3.7/site-packages/flask_executor/helpers.py", line 33, in __repr__
    target_repr = repr(self._self)
  File "~/lib/python3.7/site-packages/flask_executor/helpers.py", line 27, in __getattribute__
    return object.__getattribute__(self, attr)
  File "~/lib/python3.7/site-packages/flask_executor/helpers.py", line 15, in _self
    return object.__getattribute__(self, PROXIED_OBJECT)
AttributeError: 'Executor' object has no attribute '__proxied_object'
```

**Comment by ZairMahmood** [comment]
General use case that can cause this error is importing code that is decorated with `@EXECUTOR` but the executor itself has not initialized as it's yet to come as part of a configuring extensions.

**Comment by dchevell** [comment]
Hey @ZairMahmood , I've added a test for using the executor to decorate jobs prior to app initialisation (or just calling it directly, e.g. if one were inspecting the object, looking at the repr, etc) and modified the underlying InstanceProxy class that wraps calls to the `concurrent.futures.[Thread|Process]PoolExecutor` to ensure it behaves prior to app initialisation. Unsurprisingly, decorated jobs that try to run prior to app initialisation will fail. 

I'll update to version 0.9.3 shortly, let me know if this works for you.

**Comment by dchevell** [comment]
This has been released - closing as resolved. Let me know if you find any more issues
